# Generated by Django 6.0.3 on 2026-04-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_github_contact_linkedin_contact_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
