# Generated by Django 6.0.3 on 2026-04-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_contact_email_contact_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='back_card',
            field=models.ImageField(blank=True, null=True, upload_to='cards/back/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='front_card',
            field=models.ImageField(blank=True, null=True, upload_to='cards/front/'),
        ),
    ]
