# Generated by Django 6.0.3 on 2026-04-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_back_card_contact_front_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='github',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='website',
        ),
    ]
