# Generated by Django 6.0.3 on 2026-04-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_admin_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='New Admin', max_length=255),
        ),
    ]
