# Generated by Django 6.0.3 on 2026-04-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_admin_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='phones',
        ),
    ]
