# Generated by Django 6.0.3 on 2026-04-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_rename_phone_contact_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
